[profile.release]
codegen-units = 1
overflow-checks = false
panic = "abort"
opt-level = 3
debug = false
lto = true

[workspace]
members = [
    "turn",
    "webrtc_base",
    "lib/sdp",
    "lib/rtp",
    "lib/srtp",
    "lib/stun",
    "lib/convert",
    "lib/transport"
]
