[package]
name = "quasipaa"
version = "0.1.0"
authors = ["Mr.Panda <xivistudios@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.4"
futures = "0.3"
rml_rtmp = "0.3.0"

[dependencies.tokio]
version = "0.2"
features = ["full"]

[dependencies.tokio-util]
version = "0.3.1"
features = ["codec"]
