[package]
name = "turn"
version = "0.1.0"
edition = "2018"
authors = [
    "Mr.Panda <xivistudios@gmail.com>",
    "huangjj27 <huangjj.27@qq.com>"
]
description = """
 __  __ __     __ _____  _______  _____  _____  ______  _______  _____   _______  _    _  _____   _   _ 
 |  \\/  |\\ \\   / // ____||__   __||_   _|/ ____||  ____||__   __||_   _| |__   __|| |  | ||  __ \\ | \\ | |
 | \\  / | \\ \\_/ /| (___     | |     | | | |     | |__      | |     | |      | |   | |  | || |__) ||  \\| |
 | |\\/| |  \\   /  \\___ \\    | |     | | | |     |  __|     | |     | |      | |   | |  | ||  _  / | . ` |
 | |  | |   | |   ____) |   | |    _| |_| |____ | |____    | |    _| |_     | |   | |__| || | \\ \\ | |\\  |
 |_|  |_|   |_|  |_____/    |_|   |_____|\\_____||______|   |_|   |_____|    |_|    \\____/ |_|  \\_\\|_| \\_|
                                                                                                                                                                                                   
"""

[dependencies]
stun = { path = "../lib/stun" }
random_port = { path = "../lib/random_port" }
tokio = { version = "1", features = ["full"] }
structopt = { version = "0.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.61"
async-nats = "0.9.9"
env_logger = "0.8.2"
num_cpus = "1.13.0"
toml = "0.5.7"
log = "0.4.11"
bytes = "1"
anyhow = "1.0"
rand = "0.7"
