name: Mysticeti Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.4
      name: Setup Node.js environment
      with:
        node-version: 12
    - name: Run tests
      run: |
        npm install
        npm run test